// Auto-generated by scripts/generate-embedded-artifacts.ts
// Do not edit manually — re-run the script to update.

/**
 * Canonical artifact templates embedded as string constants.
 * Keys are relative paths within artifacts/variants/backlog-json/.
 */
export const EMBEDDED_ARTIFACTS: ReadonlyMap<string, string> = new Map([
  [
    ".rauf/RAUF.md.tmpl",
    `# Rauf — Per-Iteration Instructions

<!-- rauf:managed:start -->

## Verification Commands

Before marking any task as complete, run the full verification pipeline:

\`\`\`
{{verifyCommand}}
\`\`\`

Individual commands:
- Test: \`{{testCommand}}\`
- Typecheck: \`{{typecheckCommand}}\`
- Lint: \`{{lintCommand}}\`
- Build: \`{{buildCommand}}\`
- Format: \`{{formatCommand}}\`

If any command is not configured (empty), skip it.
{{verificationWarning}}
<!-- rauf:managed:end -->

## Workflow

1. You are one iteration of an autonomous coding loop
2. Read the backlog — find the current \`in_progress\` item
   (The Active Backlog Root section in the prompt tells you the exact path)
3. Read the item's \`acceptanceCriteria\` — each must pass
4. Read \`progress.md\` for context from previous iterations
5. Implement the task
6. Run verification: \`{{verifyCommand}}\`
7. Leave your changes in the working tree — do NOT commit. The iteration agent never commits or stages; the loop runner owns the commit (it commits as \`[rauf] <id>: <title>\` after you signal \`RAUF_DONE\`).
8. Output your exit signal on a line by itself, as your final line:
   - \`RAUF_DONE\` — all criteria met, verification passes
   - \`RAUF_BLOCKED:<reason>\` — cannot proceed, explain why
   - \`RAUF_NEEDS_HUMAN:<reason>\` — need human decision or input
   - \`RAUF_REVIEW:<json>\` — review pass only (a normal work iteration does not
     emit this); JSON matching the \`ReviewPayload\` schema.

   Putting the signal last is the safest habit, but it does not have to be
   strictly the final line: the runner scans backwards from the end and uses the
   **last** signal line, so trailing text after it (a commit message, a summary)
   does **not** break detection.

   If you emit **no** recognized signal, the runner does **not** auto-block the
   item — it classifies the outcome by exit context (clean / non-zero / timeout /
   usage-limit), logs the tail of your output, and reconciles any already-committed
   work. (Emitting a signal is still strongly preferred.)

## Model Selection

The runner resolves which model drives an iteration by this precedence
(highest wins):

\`item.model\` > \`--model\` / run options > project default > provider default

- \`item.model\` — the selected backlog item's \`model\` field (per-task override).
- \`--model\` / run options — the per-run override (\`rauf loop run --model …\`, or
  the project's configured run options).
- project default — the project's configured default model.
- provider default — if none of the above is set, no model is forced and the
  provider/CLI uses its own configured default.

\`rauf loop run --no-model\` (alias \`--model none\`) ignores \`item.model\` for that
run, so resolution drops to \`--model\` > project default > provider default. Use it
to run a backlog whose items carry Claude-only tier aliases under a non-Claude
\`--agent\` without editing \`backlog.json\`.

## Agent Delegation

Some backlog items include an \`agentDelegation\` field with guidance for parallel execution.
When present:
- If your host agent provides a subagent/delegation mechanism, use it to spawn a subagent for
  each subtask listed; if it does not, complete the subtasks inline in the main session
- Follow the \`strategy\` and \`recommendedConcurrency\` hints
- Give each subtask clear, self-contained instructions including relevant file paths
- Complete **all** subtasks before running final verification
- You (the main agent) own the exit signal — delegated subtasks do not emit RAUF_DONE/RAUF_BLOCKED
- If a subtask fails, assess whether the overall task can still be completed

Items may also include a \`specReferences\` field listing paths to specification documents. Read these before starting work.

## Important Rules

- Work on ONE item only — the current \`in_progress\` item
- Do NOT run \`git commit\` or \`git add\` — the iteration agent never commits or stages; the loop runner owns the commit. Committing yourself causes a duplicate commit and triggers per-iteration commit hooks.
- Do NOT modify \`backlog.json\` — the loop runner manages status
- Do NOT modify \`state.json\` — the loop runner manages state
- DO read \`progress.md\` for accumulated learnings
- DO append new learnings to \`progress.md\` if you discover important patterns
- The backlog.json file is your source of truth for what to work on
- Any subagents/subtasks you run internally are your own planning — they don't affect the backlog

## Project-Specific Instructions
<!-- Add custom instructions below this line — they survive rauf update -->
`,
  ],
  [
    ".rauf/REVIEW.md.tmpl",
    `# Rauf — Post-Loop Review Pass

You are a review agent auditing work completed by an autonomous coding loop. Your job is to verify that completed items genuinely meet their acceptance criteria and that no issues were introduced.

## Verification Commands

Run the full verification pipeline first:

\`\`\`
{{verifyCommand}}
\`\`\`

## Completed Items to Review

{{completedItemsDetail}}

## Git Diff of All Changes

\`\`\`diff
{{gitDiff}}
\`\`\`

## Progress Log

\`\`\`
{{progressContent}}
\`\`\`

## Review Instructions

1. **Run verification commands** above and note any failures
2. **For each completed item**, check:
   - All acceptance criteria are genuinely met (not just superficially)
   - Edge cases are handled
   - No regressions introduced
   - Tests cover the new behavior
   - Code style is consistent with the project
   - No TODOs or placeholder code left behind
3. **Look for cross-item issues:**
   - Integration problems between independently-completed items
   - Conflicting changes or duplicated logic
   - Missing imports or broken references

## Output

If you find issues that need fixing, output on a single line:

\`\`\`
RAUF_REVIEW:{"items":[{"type":"bug","priority":2,"title":"Fix: <short description>","description":"<detailed description of what's wrong and how to fix it>","acceptanceCriteria":["<specific criterion>"]}],"summary":"<1-2 sentence summary of all issues found>"}
\`\`\`

Each item in the \`items\` array must have:
- \`type\`: "bug", "refactor", "feature", or "chore"
- \`priority\`: 1-4 (1=critical, 2=high, 3=medium, 4=low)
- \`title\`: Short description prefixed with "Fix: " or "Review: "
- \`description\`: Detailed explanation of the issue and suggested fix
- \`acceptanceCriteria\`: Array of specific, verifiable criteria

If everything looks good and all checks pass, output:

\`\`\`
RAUF_DONE
\`\`\`

**IMPORTANT:** Be thorough but pragmatic. Only create fix items for genuine issues — not style preferences or minor nitpicks. Focus on correctness, test coverage gaps, and integration problems.
`,
  ],
  [
    ".rauf/backlog.json",
    `{
  "$schema": "https://raw.githubusercontent.com/garygentry/rauf/main/schemas/backlog.schema.json",
  "project": "",
  "description": "",
  "items": []
}
`,
  ],
  [
    ".rauf/backlog.schema.json",
    `{
  "type": "object",
  "properties": {
    "schemaVersion": {
      "type": "string",
      "default": "1"
    },
    "project": {
      "type": "string",
      "description": "Project name (human-readable)"
    },
    "description": {
      "type": "string",
      "description": "Brief description of the project and its goals"
    },
    "items": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1,
            "description": "Zero-padded sequential ID (e.g. '001', '042'). Never reused."
          },
          "type": {
            "type": "string",
            "enum": [
              "bug",
              "bugfix",
              "refactor",
              "feature",
              "chore",
              "test"
            ],
            "description": "Work category"
          },
          "priority": {
            "type": "integer",
            "minimum": 1,
            "maximum": 4,
            "description": "1 = highest priority, 4 = lowest"
          },
          "title": {
            "type": "string",
            "minLength": 1,
            "description": "Short imperative title"
          },
          "description": {
            "type": "string",
            "description": "Full description of the work to be done"
          },
          "acceptanceCriteria": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Checklist items — each must pass before marking done"
          },
          "status": {
            "type": "string",
            "enum": [
              "pending",
              "in_progress",
              "done",
              "blocked"
            ],
            "description": "Current lifecycle state"
          },
          "completedAt": {
            "type": [
              "string",
              "null"
            ],
            "description": "ISO 8601 timestamp set when status becomes 'done'"
          },
          "blockedReason": {
            "type": "string",
            "description": "Explanation when status is 'blocked'"
          },
          "needsHuman": {
            "type": "boolean"
          },
          "deferred": {
            "type": "boolean"
          },
          "humanAnswer": {
            "type": "string"
          },
          "dependsOn": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "IDs of items that must be 'done' before this can start"
          },
          "notes": {
            "type": "string",
            "description": "Free-text context, links, or hints for the agent"
          },
          "estimatedIterations": {
            "type": "integer",
            "exclusiveMinimum": 0,
            "description": "Expected number of loop iterations to complete"
          },
          "model": {
            "type": "string",
            "description": "Per-item model override passed to the selected provider. Omit by default for portability. Claude tier aliases such as 'opus', 'sonnet', and 'opus[1m]' are Claude-only and may fail under non-Claude agents."
          },
          "agentDelegation": {
            "type": "object",
            "properties": {
              "recommendedConcurrency": {
                "type": "integer",
                "minimum": 2
              },
              "strategy": {
                "type": "string"
              },
              "subtasks": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            },
            "additionalProperties": false
          },
          "specReferences": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "provider": {
            "type": "string"
          },
          "source": {
            "type": "string",
            "enum": [
              "human",
              "review"
            ]
          },
          "reviewBatch": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "type",
          "priority",
          "title",
          "description",
          "acceptanceCriteria",
          "status"
        ],
        "additionalProperties": false
      },
      "description": "Ordered list of backlog items"
    }
  },
  "required": [
    "project",
    "description",
    "items"
  ],
  "additionalProperties": false,
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/garygentry/rauf/main/schemas/backlog.schema.json",
  "title": "Rauf Backlog",
  "description": "Task backlog for a rauf autonomous coding loop project"
}
`,
  ],
  [
    ".rauf/progress.md",
    `# Progress & Learnings

## Codebase Patterns
<!-- Durable, project-wide patterns worth remembering across iterations.
     Append a bullet when you discover a convention, gotcha, or reusable approach. -->

## Session Log
<!-- Append ONE entry per iteration, newest at the bottom. Use this format: -->

<!--
### <item-id> — <short title>
- **Outcome:** done | blocked | needs-human
- **What changed:** one or two lines on the files/areas touched.
- **Learnings:** any gotcha, decision, or pattern a future iteration should know.
- **Follow-ups:** anything intentionally left undone (or "none").
-->
`,
  ],
  [
    "AGENTS_ADDON.md",
    `<!-- rauf:agents:start -->

## Autonomous Loop (Rauf)

This repository uses **rauf**, an autonomous coding loop. When you are running as a
rauf loop iteration, follow these operational rules. They are host-agnostic — they
apply whichever coding agent (Claude, Codex, Gemini, …) drives the iteration.

### Reading Your Task
1. Read \`.rauf/RAUF.md\` for detailed per-iteration instructions
2. Read the backlog (\`.rauf/backlog.json\`) — find the current \`in_progress\` item
3. The item's \`acceptanceCriteria\` define "done" for this iteration

### Working
4. Implement the changes described in the item's description
5. Follow acceptance criteria precisely — each one must pass
6. Run the verification command before considering work complete

### Completing
7. If all acceptance criteria pass: output \`RAUF_DONE\` as your final line
8. If blocked (missing dependency, unclear requirement): output \`RAUF_BLOCKED:<reason>\`
9. If human input needed (API key, design decision): output \`RAUF_NEEDS_HUMAN:<reason>\`
10. Do NOT commit or stage — the iteration agent never commits or stages; the loop runner owns the commit. Leave your changes in the working tree.

> Output the signal on a line by itself, as your final line — that's the safest
> habit. The runner scans backwards from the end and uses the **last** signal
> line, so trailing text after it (a commit message, a summary) does **not** break
> detection.

### Rules
- ONE item per iteration — do not work on multiple items
- Do not modify \`backlog.json\` — the loop runner manages status
- Do not modify \`state.json\` — the loop runner manages state
- Read \`progress.md\` for accumulated project learnings
- Append new learnings to \`progress.md\` if you discover important patterns

### Delegation
- If a backlog item carries \`agentDelegation\` and your host agent provides a
  subagent/delegation mechanism, use it to parallelize the independent subtasks;
  if it does not, complete the subtasks inline in the main session.
- You (the main agent) own the \`RAUF_*\` exit signal — delegated subtasks do not emit it.

### Model Selection
The runner picks the model by precedence (highest wins):
\`item.model\` > \`--model\` / options > project default > provider default.
(\`rauf loop run --no-model\` ignores \`item.model\` for one run — useful for running
a backlog whose items carry Claude-only tier aliases under a non-Claude \`--agent\`.)
<!-- rauf:agents:end -->
`,
  ],
  [
    "CLAUDE_ADDON.md",
    `<!-- rauf:start -->

## Autonomous Loop (Rauf)

When running as a rauf loop iteration, follow these operational rules:

### Reading Your Task
1. Read \`RAUF.md\` for detailed per-iteration instructions
2. Read the backlog — find the current \`in_progress\` item
3. The item's \`acceptanceCriteria\` define "done" for this iteration

### Working
4. Implement the changes described in the item's description
5. Follow acceptance criteria precisely — each one must pass
6. Run the verification command before considering work complete

### Completing
7. If all acceptance criteria pass: output \`RAUF_DONE\` as your final line
8. If blocked (missing dependency, unclear requirement): output \`RAUF_BLOCKED:<reason>\`
9. If human input needed (API key, design decision): output \`RAUF_NEEDS_HUMAN:<reason>\`
10. Do NOT commit or stage — the iteration agent never commits or stages; the loop runner owns the commit. Leave your changes in the working tree.

> Output the signal on a line by itself, as your final line — that's the safest
> habit. The runner scans backwards from the end and uses the **last** signal
> line, so trailing text after it (a commit message, a summary) does **not** break
> detection.
>
> \`RAUF_REVIEW:<json>\` is emitted only by a review pass, not a normal work
> iteration. If you emit no recognized signal, the runner does **not** auto-block
> the item — it classifies the outcome by exit context and reconciles committed
> work.

### Rules
- ONE item per iteration — do not work on multiple items
- Do not modify \`backlog.json\` — the loop runner manages status
- Do not modify \`state.json\` — the loop runner manages state
- Read \`progress.md\` for accumulated project learnings
- Append new learnings to \`progress.md\` if you discover important patterns

### Model Selection

The runner picks the model by precedence (highest wins):
\`item.model\` > \`--model\` / options > project default > provider default.
(\`rauf loop run --no-model\` ignores \`item.model\` for one run — useful for running
a Claude-aliased backlog under a non-Claude \`--agent\`.)

### Delegation (Claude Code)

In Claude Code, when a backlog item carries \`agentDelegation\`, use the **Task** tool to spawn
sub-agents for the independent subtasks, then wait for all of them before final verification. You
(the main agent) still own the \`RAUF_*\` exit signal — sub-agents do not emit it. The shared
\`RAUF.md\` guidance is host-agnostic; this Task-tool note is the Claude-specific specialization.
<!-- rauf:end -->
`,
  ],
  [
    "CLAUDE_GREENFIELD.md.tmpl",
    `# {{projectName}}

## Overview
{{projectDescription}}

## Tech Stack
{{stackDescription}}

## Project Structure
<!-- Describe the intended project structure here, or let the agent establish it -->

## Key Requirements
{{requirements}}

## Development Conventions
<!-- Add coding style, naming conventions, architectural decisions here -->

## Verification Commands
- Test: \`{{testCommand}}\`
- Typecheck: \`{{typecheckCommand}}\`
- Lint: \`{{lintCommand}}\`
- Build: \`{{buildCommand}}\`
- Full verify: \`{{verifyCommand}}\`

---

<!-- rauf:start -->

## Autonomous Loop (Rauf)

When running as a rauf loop iteration, follow these operational rules:

### Reading Your Task
1. Read \`RAUF.md\` for detailed per-iteration instructions
2. Read the backlog — find the current \`in_progress\` item
3. The item's \`acceptanceCriteria\` define "done" for this iteration

### Working
4. Implement the changes described in the item's description
5. Follow acceptance criteria precisely — each one must pass
6. Run the verification command before considering work complete

### Completing
7. If all acceptance criteria pass: output \`RAUF_DONE\` as your final line
8. If blocked (missing dependency, unclear requirement): output \`RAUF_BLOCKED:<reason>\`
9. If human input needed (API key, design decision): output \`RAUF_NEEDS_HUMAN:<reason>\`
10. Do NOT commit or stage — the iteration agent never commits or stages; the loop runner owns the commit. Leave your changes in the working tree.

> Emit the signal on a line by itself. The runner scans backwards from the end and
> uses the **last** signal line, so trailing text (a commit message, a summary)
> does **not** break detection.
>
> \`RAUF_REVIEW:<json>\` is emitted only by a review pass. If you emit no recognized
> signal, the runner does **not** auto-block — it classifies by exit context and
> reconciles committed work.

### Rules
- ONE item per iteration — do not work on multiple items
- Do not modify \`backlog.json\` — the loop runner manages status
- Do not modify \`state.json\` — the loop runner manages state
- Read \`progress.md\` for accumulated project learnings
- Append new learnings to \`progress.md\` if you discover important patterns

### Model Selection

The runner picks the model by precedence (highest wins):
\`item.model\` > \`--model\` / options > project default > provider default.
(\`rauf loop run --no-model\` ignores \`item.model\` for one run — useful for running
a Claude-aliased backlog under a non-Claude \`--agent\`.)
<!-- rauf:end -->
`,
  ],
]);

/**
 * Retrieve an embedded artifact by its relative path.
 * Throws if the artifact is not found (programming error).
 */
export function getEmbeddedArtifact(relativePath: string): string {
  const content = EMBEDDED_ARTIFACTS.get(relativePath);
  if (content === undefined) {
    throw new Error(
      `Embedded artifact not found: "${relativePath}". \nAvailable: ${[...EMBEDDED_ARTIFACTS.keys()].join(", ")}`,
    );
  }
  return content;
}
