// Auto-generated by scripts/generate-raufmd-shipped.ts — do not edit.
// Canonical hashes (see raufmd-history.ts) of every pre-ownership RAUF.md.tmpl rauf has shipped.
// Fixtures: src/__fixtures__/raufmd-shipped/<first version>.md.tmpl

export interface ShippedRaufMdHash {
  sha256: string;
  versions: readonly string[];
}

export const SHIPPED_RAUF_MD_HASHES: readonly ShippedRaufMdHash[] = [
  {
    sha256: "e50042fc5dcc95cf2ce51dc69690ad03fcd79299dcacf9d1a761efeda3b7af9b",
    versions: ["v0.3.0-rc.1", "v0.3.0-rc.2", "v0.3.0", "v0.4.0"],
  },
  {
    sha256: "d56a0f32d1579bf51cfda3fd886e19b7e17dcbbd0438fc0f8b9c2a35798a133b",
    versions: ["v0.5.0"],
  },
  {
    sha256: "2b9f7513e4af9a53a2bc47cfa8c1747f12838d0d1ef11bebac8653dc99f3f24f",
    versions: ["v0.6.0", "v0.7.0"],
  },
  {
    sha256: "53774e380ea57f080f6800a7c74b25e07eb1cb420d59d98d91335c14f0cf9153",
    versions: ["v0.8.0", "v0.8.1"],
  },
  {
    sha256: "8abe8c6f7e7891bc496cbad4336edac1efabc44b6ee8f973032e6ef56367b468",
    versions: [
      "v0.9.0",
      "v0.10.0",
      "v0.10.1",
      "v0.11.0",
      "v0.12.0",
      "v0.12.1",
      "v0.13.0",
      "v0.14.0",
    ],
  },
  {
    sha256: "f18bbe1c997ea824fb2021312709f617f0c5ad90a2697dd42f679e5166a6410d",
    versions: ["v0.15.0"],
  },
  {
    sha256: "332e83f8db27afe4ee6e7c20933067f26ba7ae7968be0f87240be868e487b4c1",
    versions: ["v0.16.0", "v0.16.1", "v0.17.0", "v0.17.1"],
  },
  {
    sha256: "a0a160b6456d03c5c6c50de23bc32e6bc843585b091d1f05862d7fc9794fca60",
    versions: ["v0.18.0"],
  },
];
