#!/usr/bin/env bun
/**
 * generate-embedded-assets.ts
 *
 * Reads the Vite build output from packages/web/build/ and generates
 * packages/web/src/server/embedded-assets.ts containing their content
 * as string constants. This allows the compiled binary to serve the
 * React SPA without filesystem access.
 *
 * Usage: bun run scripts/generate-embedded-assets.ts
 */

import * as fs from "node:fs";
import * as path from "node:path";

const REPO_ROOT = path.resolve(import.meta.dirname, "..");
const BUILD_DIR = path.join(REPO_ROOT, "packages", "web", "build");
const OUTPUT_FILE = path.join(REPO_ROOT, "packages", "web", "src", "server", "embedded-assets.ts");

/** MIME type lookup by file extension */
const MIME_TYPES: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".ico": "image/x-icon",
  ".txt": "text/plain; charset=utf-8",
};

/** Recursively collect all files in a directory, returning relative paths */
function collectFiles(dir: string, base: string = dir): string[] {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  const files: string[] = [];

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...collectFiles(fullPath, base));
    } else if (entry.isFile()) {
      files.push(path.relative(base, fullPath));
    }
  }

  return files.sort();
}

/** Escape a string for embedding in a TypeScript template literal */
function escapeForTemplateLiteral(content: string): string {
  return content.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

function main(): void {
  if (!fs.existsSync(BUILD_DIR)) {
    // eslint-disable-next-line no-console
    console.error(`Build directory not found: ${BUILD_DIR}`);
    // eslint-disable-next-line no-console
    console.error("Run 'vite build' in packages/web first.");
    process.exit(1);
  }

  const files = collectFiles(BUILD_DIR);
  const entries: string[] = [];

  for (const relativePath of files) {
    const fullPath = path.join(BUILD_DIR, relativePath);
    const content = fs.readFileSync(fullPath, "utf-8");
    const escaped = escapeForTemplateLiteral(content);
    entries.push(`  [${JSON.stringify(relativePath)}, \`${escaped}\`]`);
  }

  const output = `/* eslint-disable */
// Auto-generated by scripts/generate-embedded-assets.ts
// Do not edit manually — re-run the script to update.

const MIME_TYPES: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".ico": "image/x-icon",
  ".txt": "text/plain; charset=utf-8",
};

/**
 * Compiled React SPA assets embedded as string constants.
 * Keys are relative paths within the Vite build output (packages/web/build/).
 */
export const EMBEDDED_ASSETS: ReadonlyMap<string, string> = new Map([
${entries.join(",\n")},
]);

/**
 * Get the MIME type for an asset path based on its file extension.
 */
export function getAssetMimeType(assetPath: string): string {
  const ext = "." + assetPath.split(".").pop();
  return MIME_TYPES[ext] ?? "application/octet-stream";
}

/**
 * Retrieve an embedded asset by its relative path.
 * Returns undefined if the asset is not found.
 */
export function getEmbeddedAsset(relativePath: string): string | undefined {
  return EMBEDDED_ASSETS.get(relativePath);
}
`;

  fs.writeFileSync(OUTPUT_FILE, output, "utf-8");

  // eslint-disable-next-line no-console
  console.log(`Generated ${OUTPUT_FILE} with ${files.length} embedded assets:`);
  for (const f of files) {
    // eslint-disable-next-line no-console
    console.log(`  - ${f}`);
  }
}

main();
