#!/usr/bin/env bun
/**
 * generate-raufmd-shipped.ts
 *
 * Records every distinct pre-ownership `.rauf/RAUF.md.tmpl` rauf has shipped, so the installer can
 * recognize an unedited legacy RAUF.md (see packages/core/src/raufmd-history.ts).
 *
 *   - Reads the template at every `v*` release tag (plus EXTRA_REFS for releases prepared but not
 *     yet tagged) and writes one fixture per distinct template to FIXTURES_DIR, named after the
 *     first release that shipped it.
 *   - Writes packages/core/src/raufmd-shipped-hashes.ts: the canonical hash of each fixture and the
 *     releases that shipped it.
 *
 * The list is closed: from the ownership-boundary release on, the managed block covers the whole
 * contract and `rauf update` replaces it wholesale, so no later template needs recognizing.
 *
 * Usage:
 *   bun run scripts/generate-raufmd-shipped.ts           # regenerate from git tags (needs tags)
 *   bun run scripts/generate-raufmd-shipped.ts --check   # verify fixtures vs git, hashes vs fixtures
 *
 * `pnpm gate` runs --check. CI checks out shallow with no tags, so there it is a no-op and only
 * fixtures → hashes is pinned (by raufmd-history.test.ts); locally, fetch tags to compare with git.
 */

import { execFileSync } from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";
import { legacyRaufMdHash } from "../packages/core/src/raufmd-history.js";

const REPO_ROOT = path.resolve(import.meta.dirname, "..");
const TEMPLATE_PATH = "artifacts/variants/backlog-json/.rauf/RAUF.md.tmpl";
const FIXTURES_DIR = path.join(REPO_ROOT, "packages/core/src/__fixtures__/raufmd-shipped");
const OUTPUT_FILE = path.join(REPO_ROOT, "packages/core/src/raufmd-shipped-hashes.ts");

/** The last pre-ownership release: v0.18.0's release-prep commit (#159), merged but not yet tagged. */
const EXTRA_REFS: Record<string, string> = {
  "v0.18.0": "e0a12c5",
};

function git(args: string[]): string | null {
  try {
    return execFileSync("git", args, {
      cwd: REPO_ROOT,
      encoding: "utf-8",
      stdio: ["ignore", "pipe", "ignore"],
    });
  } catch {
    return null;
  }
}

function semverKey(tag: string): number[] {
  const [core = "", pre] = tag.replace(/^v/, "").split("-");
  const nums = core.split(".").map(Number);
  // A pre-release sorts before its release.
  return [...nums, pre ? 0 : 1];
}

function compareTags(a: string, b: string): number {
  const ka = semverKey(a);
  const kb = semverKey(b);
  for (let i = 0; i < Math.max(ka.length, kb.length); i++) {
    const d = (ka[i] ?? 0) - (kb[i] ?? 0);
    if (d !== 0) return d;
  }
  return 0;
}

interface Shipped {
  /** First release that shipped this template — also the fixture's name. */
  first: string;
  versions: string[];
  content: string;
}

function collectFromGit(): Shipped[] {
  const tags = (git(["tag", "-l", "v*"]) ?? "").split("\n").filter(Boolean);
  // Without tags (CI's shallow checkout) the record cannot be rebuilt; EXTRA_REFS alone would
  // make every older fixture look unexpected.
  if (tags.length === 0) return [];
  const refs = new Map<string, string>(tags.map((t) => [t, t]));
  for (const [version, ref] of Object.entries(EXTRA_REFS)) {
    if (!refs.has(version)) refs.set(version, ref);
  }

  const byContent = new Map<string, Shipped>();
  for (const version of [...refs.keys()].sort(compareTags)) {
    const content = git(["show", `${refs.get(version)}:${TEMPLATE_PATH}`]);
    if (content === null) continue;
    const existing = byContent.get(content);
    if (existing) existing.versions.push(version);
    else byContent.set(content, { first: version, versions: [version], content });
  }
  return [...byContent.values()];
}

function fixtureName(version: string): string {
  return `${version}.md.tmpl`;
}

function renderHashesFile(shipped: Shipped[]): string {
  const entries = shipped.map((s) => {
    const hash = legacyRaufMdHash(s.content);
    if (hash === null) throw new Error(`${s.first}: template has no canonical form`);
    return `  {\n    sha256: "${hash}",\n    versions: [${s.versions.map((v) => `"${v}"`).join(", ")}],\n  },`;
  });
  return `// Auto-generated by scripts/generate-raufmd-shipped.ts — do not edit.
// Canonical hashes (see raufmd-history.ts) of every pre-ownership RAUF.md.tmpl rauf has shipped.
// Fixtures: src/__fixtures__/raufmd-shipped/<first version>.md.tmpl

export interface ShippedRaufMdHash {
  sha256: string;
  versions: readonly string[];
}

export const SHIPPED_RAUF_MD_HASHES: readonly ShippedRaufMdHash[] = [
${entries.join("\n")}
];
`;
}

function formatTs(file: string): void {
  execFileSync("npx", ["prettier", "--write", file], { cwd: REPO_ROOT, stdio: "ignore" });
}

const check = process.argv.includes("--check");
const shipped = collectFromGit();

if (!check) {
  if (shipped.length === 0) {
    console.error("No release tags found — run `git fetch --tags` first.");
    process.exit(1);
  }
  fs.rmSync(FIXTURES_DIR, { recursive: true, force: true });
  fs.mkdirSync(FIXTURES_DIR, { recursive: true });
  for (const s of shipped)
    fs.writeFileSync(path.join(FIXTURES_DIR, fixtureName(s.first)), s.content);
  fs.writeFileSync(OUTPUT_FILE, renderHashesFile(shipped));
  formatTs(OUTPUT_FILE);
  console.log(`Recorded ${shipped.length} distinct shipped RAUF.md templates:`);
  for (const s of shipped) console.log(`  - ${s.first}: ${s.versions.join(", ")}`);
} else {
  const problems: string[] = [];
  if (shipped.length === 0) {
    console.log(
      "No release tags available — skipping the git comparison (fixtures → hashes is pinned by tests).",
    );
  } else {
    const expected = new Set(shipped.map((s) => fixtureName(s.first)));
    const actual = new Set(fs.readdirSync(FIXTURES_DIR));
    for (const s of shipped) {
      const file = path.join(FIXTURES_DIR, fixtureName(s.first));
      if (!fs.existsSync(file) || fs.readFileSync(file, "utf-8") !== s.content) {
        problems.push(`fixture ${fixtureName(s.first)} differs from git`);
      }
    }
    for (const name of actual) if (!expected.has(name)) problems.push(`unexpected fixture ${name}`);
    const tmp = `${OUTPUT_FILE}.check.ts`;
    fs.writeFileSync(tmp, renderHashesFile(shipped));
    formatTs(tmp);
    const regenerated = fs.readFileSync(tmp, "utf-8");
    fs.rmSync(tmp);
    if (regenerated !== fs.readFileSync(OUTPUT_FILE, "utf-8"))
      problems.push("raufmd-shipped-hashes.ts is stale");
  }
  if (problems.length > 0) {
    console.error("Shipped RAUF.md record drift:\n" + problems.map((p) => `  - ${p}`).join("\n"));
    console.error("Run: bun run scripts/generate-raufmd-shipped.ts");
    process.exit(1);
  }
  console.log("Shipped RAUF.md record is in sync.");
}
