#!/usr/bin/env bun
/**
 * generate-embedded-artifacts.ts
 *
 * Reads all files from artifacts/variants/backlog-json/ and generates
 * packages/core/src/embedded-artifacts.ts containing their content as
 * string constants. This makes artifacts available at runtime without
 * filesystem access — essential for bun build --compile.
 *
 * Usage: bun run scripts/generate-embedded-artifacts.ts
 */

import * as fs from "node:fs";
import * as path from "node:path";

const REPO_ROOT = path.resolve(import.meta.dirname, "..");
const ARTIFACTS_DIR = path.join(REPO_ROOT, "artifacts", "variants", "backlog-json");
const OUTPUT_FILE = path.join(REPO_ROOT, "packages", "core", "src", "embedded-artifacts.ts");

/** Recursively collect all files in a directory, returning relative paths */
function collectFiles(dir: string, base: string = dir): string[] {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  const files: string[] = [];

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...collectFiles(fullPath, base));
    } else if (entry.isFile()) {
      // Skip shell scripts — they are no longer deployed as artifacts
      if (entry.name.endsWith(".sh")) continue;
      files.push(path.relative(base, fullPath));
    }
  }

  return files.sort();
}

/** Escape a string for embedding in a TypeScript template literal */
function escapeForTemplateLiteral(content: string): string {
  return content.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

function main(): void {
  const files = collectFiles(ARTIFACTS_DIR);
  const entries: string[] = [];

  for (const relativePath of files) {
    const fullPath = path.join(ARTIFACTS_DIR, relativePath);
    const content = fs.readFileSync(fullPath, "utf-8");
    const escaped = escapeForTemplateLiteral(content);
    entries.push(`  [${JSON.stringify(relativePath)}, \`${escaped}\`]`);
  }

  const output = `// Auto-generated by scripts/generate-embedded-artifacts.ts
// Do not edit manually — re-run the script to update.

/**
 * Canonical artifact templates embedded as string constants.
 * Keys are relative paths within artifacts/variants/backlog-json/.
 */
export const EMBEDDED_ARTIFACTS: ReadonlyMap<string, string> = new Map([
${entries.join(",\n")},
]);

/**
 * Retrieve an embedded artifact by its relative path.
 * Throws if the artifact is not found (programming error).
 */
export function getEmbeddedArtifact(relativePath: string): string {
  const content = EMBEDDED_ARTIFACTS.get(relativePath);
  if (content === undefined) {
    throw new Error(
      \`Embedded artifact not found: "\${relativePath}". \\nAvailable: \${[...EMBEDDED_ARTIFACTS.keys()].join(", ")}\`,
    );
  }
  return content;
}
`;

  fs.writeFileSync(OUTPUT_FILE, output, "utf-8");

  // eslint-disable-next-line no-console
  console.log(`Generated ${OUTPUT_FILE} with ${files.length} embedded artifacts:`);
  for (const f of files) {
    // eslint-disable-next-line no-console
    console.log(`  - ${f}`);
  }
}

main();
